version: "3.3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    image: insider-app
    container_name: insider-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - insider
    extra_hosts:
      - host.docker.internal:host-gateway

  nginx:
    image: nginx:alpine
    container_name: insider-nginx
    restart: always
    depends_on:
      - app
    networks:
      - insider
    volumes:
      - ./:/var/www/html
      - ./docker/config/conf.d:/etc/nginx/conf.d/
    ports:
      - "0.0.0.0:8000:80"

  db:
    image: postgres:14
    container_name: insider-db
    restart: unless-stopped
    environment:
      POSTGRES_USERNAME: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - insider-postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/postgres-dev-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - insider

  redis:
    image: redis:latest
    container_name: insider-redis
    restart: unless-stopped
    ports:
      - "0.0.0.0:6379:6379"
    networks:
      - insider

volumes:
  insider-postgres-data:

networks:
  insider:
    driver: bridge
